### PR TITLE
Feature/global refactor

### PR DESCRIPTION
**Pull request by clementprdhomme**
This PR is the first of a series of 2 major refactors.

It brings the following improvements:
- It removes several useless (re-)renders by grouping the changes together and waiting for a "ready" state before painting anything.
- It introduces a new loader at the page loading to fetch the layers specifications (described previously as the "ready" state).
- It re-enforces the resilience of the map, of the timeline and of the state coherence when loading the app with URL params.
- It brings back the layer-specific auto-adjusting timeline's feature (the clients will love it).
- It fixes some small issues and edge cases not covered before.

Overall, the code is better more modular and the app quicker to load and interact.

As the changes cover all the components, it'll be good if @simaob (at least) and @dhakelila could review.

### CODE REVIEW

**Comment by simaob** [comment]
I'm seeing some issues:
- Can't see tooltips;
- Can't see projects' layer;

**Comment by simaob** [comment]
Disregard my previous comment. I was using a different version of the API

**Comment by simaob** [comment]
OK, found an issue. When looking at the "number of donations" layer it's requesting the tooltip for the "amount-of-money" instead of requesting the tooltip for "number of donations".

**Comment by simaob** [comment]
We can probably increase the speed for projects layer. As it will only change yearly.

**Comment by simaob** [comment]
And make sure we merge it with Staging: https://github.com/Vizzuality/care_usa/tree/staging. With might require @dhakelila's input.

**Comment by clementprdhomme** [comment]
Regarding to the speed of the cursor, I increased it as requested. Remember that this parameter will be saved in the API when switching to the staging so you'll need to take those values.

I also fixed the issue with the tooltip.

And finally, I think we should switch to the new API once the refactors are fully merged.

**Comment by simaob** [comment]
When accessing a URL with no dates set it throws an error:

http://localhost:3000/#?mode=donations&layer=amount-of-money&startDate&endDate&region&lat=27.059125784374068&lng=-57.30468749999999&sectors[]=educ&sectors[]=emer&timelineDate=2015-05-22

**Comment by clementprdhomme** [comment]
@simaob It seems that it's an issue from the back-end because the front is always sending the same query to CartoDB and it works with the [this URL](http://localhost:3000/#?mode=donations&layer=amount-of-money&region&lat=27.059125784374068&lng=-57.30468749999999&timelineDate=2015-05-22&startDate&endDate&sectors[]=econ&sectors[]=wate).

Also, as you might have noticed, the Torque layer isn't working with the region and sectors filters yet.

**Comment by simaob** [comment]
OK, will have a look.

**Pull request merged**
