### PR TITLE
Style changed of filter button in mobile

### PR DESCRIPTION
**Pull request by bitTal**
Changes the style of the filters button and the dashboard tabs in mobile resolution.

### CODE REVIEW

**Comment by simaob** [comment]
The text inside the button doesn't seem to be centered by 1 or 2 pixels.

**Comment by dhakelila** [comment]
I see what you mean, Simao. We have an issue with that typo. Because it has a funny line-height. 
The solution would be to wrap the text inside the button with an span to be able to set a margin top to center it. 
Can you fix that, Alba?

**Comment by simaob** [comment]
I noticed that it might be the same on the top menu. (Donations | Projects)

**Comment by simaob** [comment]
so started to think that maybe it was by design! =) Sorry.. to quick on the enter.

**Comment by bitTal** [comment]
I can set a margin-top to force it.

**Comment by bitTal** [comment]
I've changed the top & bottom padding instead, I think it's right now, but if you want me to move it 1 pixel more, just tell me. By the way, I've uploaded this branch with the dashboard tabs changes too.

**Comment by simaob** [comment]
Cool, thanks! I'll have a look

**Pull request merged**
