### PR TITLE
changing timeline frecuency to match between layers of the same mode

### PR DESCRIPTION
**Pull request by dhakelila**
So... This PR solves the issue with dashboard figures changing within the same mode. 
The thing is that as "amount donated" had a interval of one week when "amount of donations" had an interval of one month, when changing between those layers, timeline cursor stayed at the same place, but date showed was not the same and either the summary numbers showed because the "real" date showing up was not the same for both of them... 

I know that the interval for each layer was not chancy, but I thing it is a bit weird to see those numbers changing when changing the layer. It seems to be a bug even if it is not.  

I left here my solution for you to consider.

### CODE REVIEW

**Comment by simaob** [comment]
While testing this I seem to have found a bug.

If I move the timeline by hand back and forth sometimes the end date doesn't match the cursor date. I think this is visible on the production and staging version as well. So it probably is not introduced by this PR, but it's somewhat related so might be worth resolving here as well.

**Comment by dhakelila** [comment]
I just update this PR to avoid the bug you mentioned. 

It was due to a "debounce" function managing the date trigger when moving the timeline cursor. 
Now, in addition to trigger the date when moving the cursor. We also send the current position of the cursor to be sure we are sending the last date.

**Comment by simaob** [comment]
I'm getting an "Invalid date" as the end date when adding sectors filters.

**Comment by dhakelila** [comment]
So, I got why that error take place. Don't able to solve it yet.
The thing is that we are triggering the "brushend" event from the timeline when changing or applying the filters. And it gets and invalid date and set it as timeline date for a second. Time enough to make an API request with that "invalid date" and make the project crash.

**Comment by simaob** [comment]
can we block the request if we have that invalid date? or something like that?

**Comment by dhakelila** [comment]
Sure. Just on it. But I would like to review why are we triggering that when changing filters.

**Comment by dhakelila** [comment]
So, finally, we saw that the initial issue fixed by this PR is not related with the last one. 
As we are fixing  it somewhere else, could you please, merge this PR, @simaob?

**Comment by simaob** [comment]
Having a look at it again =) and merging

**Pull request merged**
